### ISSUE TITLE
The binary finder doesn't work by default for Aurora on Mac

### ISSUE THREAD

**Issue by Standard8** [mozilla-jetpack/node-fx-runner#12]
When Firefox Developer Edition was created, the default install location changed from `/Applications/FirefoxAurora.app` to `/Applications/FirefoxDeveloperEdition.app`.

I don't know if we still want to support the old version or not, maybe we could either change it or add a new option? e.g. `-b dev` maybe?

**Comment by kumar303** [comment]
I think the patch in https://github.com/mozilla-jetpack/node-fx-runner/pull/11 should fix this

**Comment by bwinton** [comment]
Yep.  (I didn't remove the old one, because you _could_ still have it installed, and I made the key for the new version `firefoxdeveloperedition`, because that's what the bundle identifier uses.  Patches to alias it to `dev` or preferably `deved` would probably be accepted… :wink:)
