### ISSUE TITLE
`firefoxdeveloperedition` alias is long and named differently than the other aliases

### ISSUE THREAD

**Issue by ariasuni** [mozilla-jetpack/node-fx-runner#43]
All aliases of non-release editions of Firefox are named after the part that goes after Firefox:

- Firefox Beta → `beta`
- Firefox Aurora → `aurora`
- Firefox Nightly → `nightly`

It follows that the alias for Firefox Developer Edition should be `developer-edition`. This would also make it more useful as an alias because it’s less text to type.

**Comment by Rob--W** [comment]
I propose "deved" as alias, because it is shorter and also commonly used by Mozillians.

What is your use case? Are you using this library directly, or is it affecting you elsewhere (e.g. in `web-ext`)?

**Comment by ariasuni** [comment]
Personally, it’s the first time I heard of `deved` and it sounds obscure.

What about `dev-edition`? Easy to understand, reasonably short.

**Comment by ariasuni** [comment]
Also I see that `deved` is not really used as is, it’s more `DevEd` and I can only found occurrences of it on obscure pages of Mozilla Wiki, while you the expression `Dev Edition` is used on https://www.mozilla.org/en-US/firefox/developer/.

Anyway if you still think `deved` is a better alias, then I’ll put that in my PR.

**Comment by Rob--W** [comment]
I've also seen DevEd on community-supported support forums such as Reddit (/r/firefox).

`devedition` sounds like a reasonable short alternative if you really have a feud against deved ;)

**Comment by ariasuni** [comment]
I don’t know, I feel like `deved` isn’t intuitive to remember. It’s very frequent to abbreviate developer to simply dev, not so much for edition.

If that was me, I’d a very unscientific poll on social media to have an idea of what people prefer in term and shortness and memorability, to have a rough idea of how it might work for other people.

But maybe that’s just overthinking on my part for a detail.

**Comment by Rob--W** [comment]
I want at least one short name, `deved` or `devedition`.

It's a bit confusing to follow the discussion because it's split between this issue and the pull request (#44). The PR has not been updated despite the comments there: https://github.com/mozilla-jetpack/node-fx-runner/pull/44#issuecomment-611822805 . Please update the PR, then I'll review it.

**Comment by ariasuni** [comment]
Oh, sorry, I was waiting for a «final» decision before changing my PR, so I’m still not sure what I’m supposed to do.

**Comment by Rob--W** [comment]
Current PR + https://github.com/mozilla-jetpack/node-fx-runner/pull/44#issuecomment-614666904

I'm fine with "deved" or "devedition", as long as it is shorter than "firefoxdeveloperedition"
